Models/Tasks.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace webapp.Models
{
    public class Tasks
    {

        public int Id { set; get; }

        [Required]
        [Display(Name = "Nome")]
        public string Name { set; get; }

        [Required]
        [Display(Name = "Descrição")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "DeadLine")]
        public DateTime DeadLine { get; set; }

        [Required]
        [Display(Name = "Classisficação")]
        public int Classification { get; set; }
    }
}

Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webapp.Models;

namespace webapp.Controllers
{
    public class TaskController : Controller
    {
        private readonly ApplicationDbContext _db;

        private static SelectListItem[] DropDownOptions = new[]{
                new SelectListItem(){ Value = "0", Text = "Nice"},
                new SelectListItem(){ Value = "1", Text = "There's time"},
                new SelectListItem(){ Value = "2", Text = "Danger"},
                new SelectListItem(){ Value = "3", Text = "Late"}
         };

        public TaskController()
        {
            this._db = ApplicationDbContext.Create();
        }

        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                if (TempData["TaskValidation"] != null)
                {
                    ViewBag.Error = TempData["TaskValidation"].ToString();
                }

                ViewBag.PageName = "Criar nova tarefa";
                ViewData["Classification"] = DropDownOptions;

                return View();
            }

            return RedirectToAction("Login", "Account");
        }

        public ActionResult Store(Tasks model)
        {
            if (ModelState.IsValid)
            {
                this._db.Task.Add(model);
                this._db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            else
            {
                TempData["TaskValidation"] = "Seria massa se você preenchesse TODOS os campos!";
            }

            return RedirectToAction("Create");
        }
        
        [HttpGet]
        public ActionResult Update(int id)
        {
            Tasks Task = this._db.Task.Find(id);

            ViewData["Date"] = Task.DeadLine.ToString("yyyy-MM-dd").Substring(0, 10);
            ViewData["Classification"] = DropDownOptions;
            ViewBag.PageName = "Modificar tarefa";

            return View(Task);
        }

        [HttpPost]
        public ActionResult Update(Tasks Task)
        {
            Tasks DBTask = this._db.Task.Find(Task.Id);
            DBTask.Name = Task.Name;
            DBTask.Description = Task.Description;
            DBTask.DeadLine = Task.DeadLine;
            DBTask.Classification = Task.Classification;
            this._db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Delete(int id)
        {
            Tasks Tasks = this._db.Task.Find(id);
            this._db.Task.Remove(Tasks);
            this._db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Task/Create.cshtml
@model webapp.Models.Tasks

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-5 offset-md-3">
        <div class ="card">

            <div class="card-body">
                <div class="col-md-10 offset-md-1">
                    <h4>
                        @ViewBag.PageName
                    </h4>
                </div>

                @using (Html.BeginForm("Store", "Task", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {

                    @Html.AntiForgeryToken()

                    <div class="form-group col-md-10 offset-md-1">

                        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })

                    </div>

                    <div class="form-group col-md-10 offset-md-1">

                        @Html.LabelFor(m => m.Description, new { @class = "control-label" })
                        @Html.TextArea("Description", null, new { @class = "form-control" })

                    </div>

                    <div class="form-group col-md-10 offset-md-1">
                        @Html.DropDownList("Classification", null, new { @class = "custom-select" })
                    </div>

                    <div class="form-group col-md-10 offset-md-1">

                        @Html.LabelFor(m => m.DeadLine, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.DeadLine, new { type = "date", @class = "form-control" })

                    </div>

                    if (@ViewBag.Error != null)
                    {
                        <div class="col-md-10 offset-md-1">
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.Error
                            </div>
                        </div>
                    }

                    <div class="col-md-10 offset-md-1">
                        <input type="submit" class="btn btn-primary" value="Criar" />
                    </div>

                }
            </div>
        </div>
    </div>
</div>

Views/Task/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">

    <div class="card-body">

    </div>

</div>

Views/Task/Update.cshtml
@model webapp.Models.Tasks

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="row">
        <div class="col-md-5 offset-md-3">
            <div class="card">

                <div class="card-body">
                    <div class="col-md-10 offset-md-1">
                        <h4>
                            @ViewBag.PageName
                        </h4>
                    </div>

                    @using (Html.BeginForm("Update", "Task", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {

                        @Html.AntiForgeryToken()

                        <div class="form-group col-md-10 offset-md-1">

                            @Html.LabelFor(m => m.Name, new { @class = "control-label"})
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", value = Model.Name })

                        </div>

                        <div class="form-group col-md-10 offset-md-1">

                            @Html.LabelFor(m => m.Description, new { @class = "control-label" })
                            @Html.TextArea("Description", null, new { @class = "form-control", value = Model.Description  })

                        </div>

                        <div class="form-group col-md-10 offset-md-1">
                            @Html.DropDownList("Classification", null, new { @class = "custom-select", value = Model.Classification})
                        </div>

                        <div class="form-group col-md-10 offset-md-1">

                            <input type="hidden" value="@ViewData["Date"]" id="DateTime" />
                            <input type="hidden" value="@Model.Classification" id="HiddenClassification" />

                            @Html.LabelFor(m => m.DeadLine, new { @class = "control-label" })
                            @Html.TextBoxFor(m => m.DeadLine, new { type = "date", @class = "form-control" })

                        </div>

                        <div class="col-md-10 offset-md-1">
                            <input type="submit" class="btn btn-primary" value="Atualizar" />
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>